#!/bin/bash
# Quick Start Guide - Manual Testing untuk Memory Poisoning Detection System

echo "=========================================="
echo "📚 Quick Start Guide - Manual Testing"
echo "=========================================="
echo ""

echo " PREREQUISITES"
echo "----------------------------------------"
echo "1. Pastikan Python 3.10+ terinstall"
echo "2. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""

echo " QUICK TESTS"
echo "----------------------------------------"
echo ""

echo "1⃣  Test Unit (Instrumentation & Detection)"
echo "   PYTHONPATH=. pytest tests/ -v"
echo ""

echo "2⃣  Test Red-Teaming (Attack Detection)"
echo "   PYTHONPATH=. python scripts/run_red_team.py"
echo ""

echo "3⃣  Generate Attack Dataset Baru"
echo "   PYTHONPATH=. python scripts/generate_attacks.py"
echo ""

echo "4⃣  Evaluate Detector (Precision/Recall)"
echo "   PYTHONPATH=. python scripts/evaluate_detector.py"
echo ""

echo "=========================================="
echo "  INTERACTIVE DEMO (Streamlit)"
echo "=========================================="
echo ""
echo "Buka browser: http://localhost:8501"
echo "Streamlit app: src/dashboard/app.py"
echo ""
echo "Cara jalankan:"
echo "  PYTHONPATH=. streamlit run src/dashboard/app.py"
echo ""

echo " MANUAL TESTING FLOW"
echo "=========================================="
echo ""
echo "Langkah 1: Generate dataset baru"
echo "   \$ PYTHONPATH=. python scripts/generate_attacks.py --count 100"
echo ""
echo "Langkah 2: Jalankan red-teaming test"
echo "   \$ PYTHONPATH=. python scripts/run_red_team.py"
echo ""
echo "Langkah 3: Cek hasil evaluation"
echo "   \$ cat data/evaluation/detector_metrics.json"
echo ""
echo "Langkah 4: Buka dashboard"
echo "   \$ PYTHONPATH=. streamlit run src/dashboard/app.py"
echo ""
echo "Dashboard features:"
echo "  - View MemoryEvents dengan filter"
echo "  - Lihat Detection Results"
echo "  - Monitor Quarantine entries"
echo "  - Review Audit Trail"
echo ""

echo "🔧 ENVIRONMENT VARIABLES (Opsional)"
echo "=========================================="
echo ""
echo "Untuk LLM-as-Judge classification (lebih akurat):"
echo "  export OPENAI_API_KEY=sk-..."
echo "  atau"
echo "  export ANTHROPIC_API_KEY=sk-..."
echo "  atau"
echo "  export GOOGLE_API_KEY=..."
echo ""

echo " FILE STRUCTURE"
echo "=========================================="
echo ""
echo "src/"
echo "  ├── instrumentation/   # Provenance tracking"
echo "  ├── detection/         # 4-layer detection"
echo "  ├── quarantine/        # Verification workflow"
echo "  ├── audit/             # Event sourcing & rollback"
echo "  ├── vectorstore/       # Chroma DB client"
echo "  ├── dashboard/         # Streamlit UI"
echo "  └── agent_testbed/     # Test agent"
echo ""
echo "scripts/"
echo "  ├── generate_attacks.py     # Dataset generator"
echo "  ├── evaluate_detector.py    # Evaluation script"
echo "  └── run_red_team.py         # Red-teaming benchmark"
echo ""

echo " EXPECTED RESULTS"
echo "=========================================="
echo ""
echo "Dataset: 700+ samples di 10 categories"
echo "Tests:   19/19 passing"
echo "Detection Rate: ~50% (rule-based)"
echo "               ~90%+ (dengan LLM-as-judge)"
echo "False Positive: 0% (controls)"
echo ""

echo " LANGKAH SELANJUTNYA"
echo "=========================================="
echo ""
echo "1. Jalankan test suite untuk verify"
echo "2. Generate dataset untuk evaluation"
echo "3. Set API key jika mau LLM classification"
echo "4. Open dashboard untuk interaktif testing"
echo ""

echo " Selamat mencoba!"
